package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1



/**
 * Tadmin generated by hbm2java
 */
public class Tadmin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public Tadmin() {
    }

    public Tadmin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


