package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1



/**
 * Temployee generated by hbm2java
 */
public class Temployee  implements java.io.Serializable {


     private Integer id;
     private Tkantor tkantor;
     private Tkota tkota;
     private Tprov tprov;
     private String nama;
     private String alamat;
     private String kodearea;
     private String nope;

    public Temployee() {
        tprov = new Tprov();
        tkantor = new Tkantor();
        tkota = new Tkota();
    }

    public Temployee(Tkantor tkantor, Tkota tkota, Tprov tprov, String nama, String alamat, String kodearea, String nope) {
       this.tkantor = tkantor;
       this.tkota = tkota;
       this.tprov = tprov;
       this.nama = nama;
       this.alamat = alamat;
       this.kodearea = kodearea;
       this.nope = nope;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tkantor getTkantor() {
        return this.tkantor;
    }
    
    public void setTkantor(Tkantor tkantor) {
        this.tkantor = tkantor;
    }
    public Tkota getTkota() {
        return this.tkota;
    }
    
    public void setTkota(Tkota tkota) {
        this.tkota = tkota;
    }
    public Tprov getTprov() {
        return this.tprov;
    }
    
    public void setTprov(Tprov tprov) {
        this.tprov = tprov;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getKodearea() {
        return this.kodearea;
    }
    
    public void setKodearea(String kodearea) {
        this.kodearea = kodearea;
    }
    public String getNope() {
        return this.nope;
    }
    
    public void setNope(String nope) {
        this.nope = nope;
    }




}


