package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tkantor generated by hbm2java
 */
public class Tkantor  implements java.io.Serializable {


     private Integer idkantor;
     private Tprov tprov;
     private String namakantor;
     private Set<Temployee> temployees = new HashSet<Temployee>(0);
     private Set<Tkota> tkotas = new HashSet<Tkota>(0);

    public Tkantor() {
    }

	
    public Tkantor(Tprov tprov, String namakantor) {
        this.tprov = tprov;
        this.namakantor = namakantor;
    }
    public Tkantor(Tprov tprov, String namakantor, Set<Temployee> temployees, Set<Tkota> tkotas) {
       this.tprov = tprov;
       this.namakantor = namakantor;
       this.temployees = temployees;
       this.tkotas = tkotas;
    }
   
    public Integer getIdkantor() {
        return this.idkantor;
    }
    
    public void setIdkantor(Integer idkantor) {
        this.idkantor = idkantor;
    }
    public Tprov getTprov() {
        return this.tprov;
    }
    
    public void setTprov(Tprov tprov) {
        this.tprov = tprov;
    }
    public String getNamakantor() {
        return this.namakantor;
    }
    
    public void setNamakantor(String namakantor) {
        this.namakantor = namakantor;
    }
    public Set<Temployee> getTemployees() {
        return this.temployees;
    }
    
    public void setTemployees(Set<Temployee> temployees) {
        this.temployees = temployees;
    }
    public Set<Tkota> getTkotas() {
        return this.tkotas;
    }
    
    public void setTkotas(Set<Tkota> tkotas) {
        this.tkotas = tkotas;
    }




}


