package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tkota generated by hbm2java
 */
public class Tkota  implements java.io.Serializable {


     private Integer idkota;
     private Tkantor tkantor;
     private String namakota;
     private Set<Temployee> temployees = new HashSet<Temployee>(0);

    public Tkota() {
    }

	
    public Tkota(Tkantor tkantor, String namakota) {
        this.tkantor = tkantor;
        this.namakota = namakota;
    }
    public Tkota(Tkantor tkantor, String namakota, Set<Temployee> temployees) {
       this.tkantor = tkantor;
       this.namakota = namakota;
       this.temployees = temployees;
    }
   
    public Integer getIdkota() {
        return this.idkota;
    }
    
    public void setIdkota(Integer idkota) {
        this.idkota = idkota;
    }
    public Tkantor getTkantor() {
        return this.tkantor;
    }
    
    public void setTkantor(Tkantor tkantor) {
        this.tkantor = tkantor;
    }
    public String getNamakota() {
        return this.namakota;
    }
    
    public void setNamakota(String namakota) {
        this.namakota = namakota;
    }
    public Set<Temployee> getTemployees() {
        return this.temployees;
    }
    
    public void setTemployees(Set<Temployee> temployees) {
        this.temployees = temployees;
    }




}


