package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tprov generated by hbm2java
 */
public class Tprov  implements java.io.Serializable {


     private Integer idprovinsi;
     private String namaprovinsi;
     private Set<Temployee> temployees = new HashSet<Temployee>(0);
     private Set<Tkantor> tkantors = new HashSet<Tkantor>(0);

    public Tprov() {
    }

	
    public Tprov(String namaprovinsi) {
        this.namaprovinsi = namaprovinsi;
    }
    public Tprov(String namaprovinsi, Set<Temployee> temployees, Set<Tkantor> tkantors) {
       this.namaprovinsi = namaprovinsi;
       this.temployees = temployees;
       this.tkantors = tkantors;
    }
   
    public Integer getIdprovinsi() {
        return this.idprovinsi;
    }
    
    public void setIdprovinsi(Integer idprovinsi) {
        this.idprovinsi = idprovinsi;
    }
    public String getNamaprovinsi() {
        return this.namaprovinsi;
    }
    
    public void setNamaprovinsi(String namaprovinsi) {
        this.namaprovinsi = namaprovinsi;
    }
    public Set<Temployee> getTemployees() {
        return this.temployees;
    }
    
    public void setTemployees(Set<Temployee> temployees) {
        this.temployees = temployees;
    }
    public Set<Tkantor> getTkantors() {
        return this.tkantors;
    }
    
    public void setTkantors(Set<Tkantor> tkantors) {
        this.tkantors = tkantors;
    }




}


