package model;
// Generated Mar 9, 2018 1:46:23 AM by Hibernate Tools 4.3.1



/**
 * Tuser generated by hbm2java
 */
public class Tuser  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String username;
     private String password;
     private byte[] image;

    public Tuser() {
    }

	
    public Tuser(String nama, String username, String password) {
        this.nama = nama;
        this.username = username;
        this.password = password;
    }
    public Tuser(String nama, String username, String password, byte[] image) {
       this.nama = nama;
       this.username = username;
       this.password = password;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


